### ISSUE TITLE
java.util.ConcurrentModificationException

### ISSUE THREAD

**Issue by fihgus** [fihgus/Slash#29]
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.checkForComodification(Unknown Source)
	at java.util.ArrayList$Itr.next(Unknown Source)
	at slash.elements.Group.getGroups(Group.java:125)
	at slash.newIO.PermissionFile.getClosestPermission(PermissionFile.java:183)
	at slash.newIO.PermissionFile.getPermissionResult(PermissionFile.java:165)
	at slash.events.handlers.ItemRestriction.canAcquireItem(ItemRestriction.java:101)
	at slash.events.handlers.ItemRestriction.onPickupItem(ItemRestriction.java:43)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_166_ItemRestriction_onPickupItem_EntityItemPickupEvent.invoke(.dynamic)
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54)
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138)
	at net.minecraft.entity.item.EntityItem.func_70100_b_(EntityItem.java:345)
	at net.minecraft.entity.player.EntityPlayer.func_71044_o(EntityPlayer.java:609)
	at net.minecraft.entity.player.EntityPlayer.func_70636_d(EntityPlayer.java:600)
	at net.minecraft.entity.player.EntityPlayerMP.localOnLivingUpdate(EntityPlayerMP.java)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(ServerPlayerAPI.java:4891)
	at api.player.server.ServerPlayerAPI.onLivingUpdate(ServerPlayerAPI.java:4877)
	at net.minecraft.entity.player.EntityPlayerMP.func_70636_d(EntityPlayerMP.java)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.player.EntityPlayer.func_70071_h_(EntityPlayer.java:288)
	at net.minecraft.entity.player.EntityPlayerMP.localOnUpdateEntity(EntityPlayerMP.java:295)
	at api.player.server.ServerPlayerAPI.onUpdateEntity(ServerPlayerAPI.java:5111)
	at net.minecraft.entity.player.EntityPlayerMP.func_71127_g(EntityPlayerMP.java)
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:337)
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(SourceFile:137)
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(SourceFile:63)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

**Comment by fihgus** [comment]
hopefully fixed.
